"""
Name: card_library_app.py
Author: Andrew Peterson
Date: 10/23/2024
Purpose: store game scores
"""

import highscore_database
import random
from datetime import date

MENU_PROMPT = """------ Scoreboard App ------
(1) display all scores
(2) find a score by ID
(3) delete a score
(4) exit
Your selection: """

def main():
    highscore_database.create_table()
    game()
    menu()

def menu():
    while True:
        user_imput = input(MENU_PROMPT)

        if user_imput == "1":
            display_all_scores()


        elif user_imput == "2":
            display_all_scores()

            plyr_id = int(input("Enter song ID: "))

            display_score(plyr_id)

        elif user_imput == "3":
            display_all_scores()

            plyr_id = int(input("Enter song ID: "))

            highscore_database.delete_score(plyr_id)

            display_all_scores()

        elif user_imput == "4":
            break

        else:
            print("Invalid input, try again!")

def display_all_scores():
    # fetch all cards
    highscore = highscore_database.fetch_all_scores()
    for score in highscore:
        # Print each item
        scoreboard = f"ID: ({score[0]}) {score[1]} "
        scoreboard += f"{score[2]} {score[3]}  "
        print(scoreboard)

def display_score(plyr_id: int):
    highscore = highscore_database.fetch_score(plyr_id)

    for score in highscore:
        # Print each item
        scoreboard = f"ID: ({score[0]}) {score[1]} "
        scoreboard += f"{score[2]} {score[3]}  "
        print(scoreboard)

def game():
    # game generated by copilot
    number_to_guess = random.randint(1, 100)
    points = 100
    attempts = 0

    print("Welcome to the Number Guessing Game!")
    print("Guess a number between 1 and 100.")
    plyr_name = (input("Enter your name: "))
    plyr_date = date.today()

    while True:
        guess = int(input("Enter your guess: "))
        attempts += 1

        if guess < number_to_guess:
            print("Too low!")
            points -= 10
        elif guess > number_to_guess:
            print("Too high!")
            points -= 10
        else:
            print(f"Congratulations! You've guessed the right number in {attempts} attempts.")
            print(f"Your score is: {points} points")
            plyr_score = points

            highscore_database.insert_score(
                plyr_name,
                plyr_score,
                plyr_date
            )
            break

        if points <= 0:
            print("Sorry, you've run out of points. Better luck next time!")
            plyr_score = 0
            highscore_database.insert_score(
                plyr_name,
                plyr_score,
                plyr_date
            )
            break

main()