"""
Name: card_library_app.py
Author: Andrew Peterson
Date: 10/23/2024
Purpose: store game scores
"""

import highscore_database
import random
from datetime import date
from tkinter import *
from tkinter.ttk import *

MENU_PROMPT = """------ Scoreboard App ------
(1) display all scores
(2) find a score by ID
(3) delete a score
(4) exit
Your selection: """

def main():
    highscore_database.create_table()
    guessing_game = GuessingGame()
    menu()

def menu():
    while True:
        user_imput = input(MENU_PROMPT)

        if user_imput == "1":
            display_all_scores()


        elif user_imput == "2":
            display_all_scores()

            plyr_id = int(input("Enter song ID: "))

            display_score(plyr_id)

        elif user_imput == "3":
            display_all_scores()

            plyr_id = int(input("Enter song ID: "))

            highscore_database.delete_score(plyr_id)

            display_all_scores()

        elif user_imput == "4":
            break

        else:
            print("Invalid input, try again!")

def display_all_scores():
    # fetch all cards
    highscore = highscore_database.fetch_all_scores()
    for score in highscore:
        # Print each item
        scoreboard = f"ID: ({score[0]}) {score[1]} "
        scoreboard += f"{score[2]} {score[3]}  "
        print(scoreboard)

def display_score(plyr_id: int):
    highscore = highscore_database.fetch_score(plyr_id)

    for score in highscore:
        # Print each item
        scoreboard = f"ID: ({score[0]}) {score[1]} "
        scoreboard += f"{score[2]} {score[3]}  "
        print(scoreboard)

class GuessingGame:
    # game generated by copilot
    def __init__(self):
        # game generated by copilot
        self.number_to_guess = random.randint(1, 100)
        self.plyr_date = date.today()
        self.points = 100
        self.attempts = 0
        self.plyr_name = input("Enter your name: ")
        # create window
        self.root = Tk()
        self.root.title("Guessing Game")
        # create widgets via method
        self.create_widgets()
        # call mainloop
        mainloop()

    def create_widgets(self):
        self.main_frame = LabelFrame(
            self.root,
            text="Enter your guess (1 to 100)",
            relief=GROOVE
        )

        self.entry = Entry(
            self.main_frame,
            width=10
        )

        self.btn_check = Button(
            self.main_frame,
            text="guess",
            command=self.check_numbers
        )

        self.lbl_result = Label(
            self.main_frame,
            width=10,
            relief=GROOVE,
            anchor=E
        )

        self.lbl_points = Label(
            self.main_frame,
            width=10,
            relief=GROOVE,
            anchor=E
        )

        self.entry.grid(row=0, column=0)
        self.btn_check.grid(row=0, column=1)

        self.lbl_result.grid(
            row=1,
            column=0,
            sticky=EW
        )

        self.lbl_points.grid(
            row=1,
            column=1,
            sticky=EW
        )

        self.main_frame.grid_configure(padx=20, pady=20)
        for widget in self.main_frame.winfo_children():
            widget.grid_configure(padx=10, pady=10)

        self.entry.focus_set()

        self.root.bind("<Return>", self.check_numbers)
        self.root.bind("<KP_Enter>", self.check_numbers)

    def check_numbers(self, *args):
        while True:
            self.attempts = 1 + self.attempts
            self.guess = int(self.entry.get())
            if self.guess > self.number_to_guess:
                self.lbl_result.configure(text=f"{self.guess} is too high")
                self.points -= 10
                self.lbl_points.configure(text=f"{self.points}")
            elif self.guess < self.number_to_guess:
                self.lbl_result.configure(text=f"{self.guess} is too low")
                self.points -= 10
                self.lbl_points.configure(text=f"{self.points}")
            else:
                self.lbl_result.configure(f"Congratulations! You've guessed the right number in {self.attempts} attempts.")
                self.lbl_points.configure(text=f"{self.points}")
                plyr_score = self.points

                highscore_database.insert_score(
                    self.plyr_name,
                    plyr_score,
                    self.plyr_date
                )
                self.root.destroy()

            if self.points <= 0:
                self.lbl_result.configure("Sorry, you've run out of points. Better luck next time!")
                plyr_score = 0
                highscore_database.insert_score(
                    self.plyr_name,
                    plyr_score,
                    self.plyr_date
                )
                self.root.destroy()

main()